MyOnlineLibrary/Controllers/BooksCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MyOnlineLibrary.Core.Contracts;
using MyOnlineLibrary.Core.Models;
using MyOnlineLibrary.Infrastructure.Data.Models;

namespace MyOnlineLibrary.Controllers
{
    public class BooksCategoryController : Controller
    {
        private readonly IBooksService bookService;

        public IEnumerable<Category> Categories { get; private set; }

        public BooksCategoryController(IBooksService _bookService)
        {
            bookService = _bookService;
        }


        public async Task<IActionResult> Category( int Id)
        {
            var books = await bookService.GetAllAsync();
            var model = books.Where(b => b.CategoryId == Id);
            


            return View(model);
        }
       
    }
}

MyOnlineLibrary/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyOnlineLibrary.Core.Contracts;
using MyOnlineLibrary.Core.Models;
using MyOnlineLibrary.Infrastructure.Data;
using MyOnlineLibrary.Infrastructure.Data.Common;
using MyOnlineLibrary.Infrastructure.Data.Models;
using System.Collections.Generic;
using System.Security.Claims;



namespace MyOnlineLibrary.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksService bookService;

        private readonly IWebHostEnvironment _environment;
        private readonly MyOnlineLibraryDbContext context;
        private readonly IRepository repository;


        public IEnumerable<Category> Categories { get; private set; }

        public BooksController(IBooksService _bookService, IWebHostEnvironment environment
            , MyOnlineLibraryDbContext _cotext,
            IRepository _repository)
        {
            bookService = _bookService;
            _environment = environment;
            context = _cotext;
            repository = _repository;


        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await bookService.GetAllAsync();
           
            return View(model);
        }



        [HttpGet]

        public async Task<IActionResult> Add()
        {
            var model = new AddBookViewModel()
            {
                Categories = await bookService.GetCategoryAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBookViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await bookService.AddBookAsync(model);


                await context.SaveChangesAsync();





                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");

                return View(model);
            }
        }

        public async Task<IActionResult> AddToCollection(int bookId)
        {
            try
            {
                var UserId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
                await bookService.AddBookToCollectionAsync(bookId, UserId);
            }
            catch
            {
                throw;
            }

            return RedirectToAction(nameof(All));
        }


        public async Task<IActionResult> MyBooks()
        {
            var UserId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            var model = await bookService.GetMyBookAsync(UserId);

            return View("Mine", model);
        }

        public async Task<IActionResult> RemoveFromCollection(int bookId)
        {
            var UserId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            await bookService.RemoveBookFromCollectionAsync(bookId, UserId);

            return RedirectToAction(nameof(MyBooks));
        }




        [HttpGet]
        public async Task<IActionResult> Search(string query)
        {
            var result = await bookService.GetAllAsync();

            if (query == null)
            {
                return View("All", result);

            }


            var model = result.Where(b => b.Title.Contains(query) || b.Author.Contains(query));
            return View("All", model);
        }



        [HttpGet]
        public async Task<IActionResult> SearchDescription(int id)
        {
            var result = await bookService.GetAlltoDownloadAsync();
            var model = result.Where(b => b.Id == id);
            return View("BookDescription", model);
        }

        public IActionResult DownloadFile(int id)
        {
            var file = context.Files.Find(id);

            if (file == null)
            {
                return NotFound();
            }

            return File(file.Data, "application/octet-stream", file.FileName);
        }


        public async Task<IActionResult> UploadFile(int id, IFormFile[] fileUpload)
        {
            var book = await context.Books
                .Include(b => b.UploadFiles)
                .FirstOrDefaultAsync(b => b.Id == id);

            if (book == null)
            {
                return NotFound();
            }

            // Process and save the attachments, if any
            if (fileUpload != null && fileUpload.Length > 0)
            {
                foreach (var file in fileUpload)
                {
                    if (file.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await file.CopyToAsync(memoryStream);
                            var attachment = new UploadFiles
                            {
                                Data = memoryStream.ToArray(),
                                BookId = book.Id,
                                FileName = file.FileName
                            };
                            book.UploadFiles.Add(attachment);
                        }
                    }
                }

                await context.SaveChangesAsync();
            }



            return RedirectToAction("SearchDescription", new { id });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBook(int Id)
        {
            bookService.Delete(Id);


            return RedirectToAction("All"); ;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var books = await bookService.GetAllAsync();
            var book = books.FirstOrDefault(b => b.Id == Id);
            var cat = await bookService.GetCategoryAsync();


            

            var model = new AddBookViewModel()
            {
                Id = book.Id,
                Author = book.Author,
                Title = book.Title,
                ImageUrl = book.ImageUrl,
                Rating = book.Rating,
                Categories = cat,
                Description = book.Description,
                
                CategoryId = book.CategoryId,
            };






            return (model == null) ? NotFound() : View(model);
        }



        [HttpPost]
        public async Task<IActionResult>  Edit(AddBookViewModel model, int Id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await bookService.EditBookAsync(model);


                await context.SaveChangesAsync();





                return RedirectToAction("SearchDescription", new { Id });
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");

                return View(model);
            }

        }
    }




}

MyOnlineLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -My Online Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/book.css" rel="stylesheet" asp-append-version="true" />
    
</head>
<body>
    <header class="header-outer">
      
        <nav class="navbar">
            
            <div class="container-fluid">
               
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                          <div class="btn-group">
                            <div class="dropdown">
                              <a  class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="true">
                                   Category
                                </a>
                                <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-route-Id="1" asp-controller="BooksCategory" asp-action="Category">Action</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-route-Id="2" asp-controller="BooksCategory" asp-action="Category">Biography</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-route-Id="3" asp-controller="BooksCategory" asp-action="Category">Children</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-route-Id="4" asp-controller="BooksCategory" asp-action="Category">Crime</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-route-Id="5" asp-controller="BooksCategory" asp-action="Category">Fantasy</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                </ul>
                                </div>
                            </div>
                    <a asp-area="" asp-controller="Books" asp-action="All">
                        Books
                    </a>
                        <a asp-area="" asp-controller="Books" asp-action="MyBooks">
                            My Books
                        </a>
                        <a  asp-area="" asp-controller="Books" asp-action="Add" >
                            Add Books
                        </a>
                    
                        }

                <div></div>
                <div><partial name="_LoginPartial" /></div>
                </div>
             
        </nav>
        @if (User?.Identity?.IsAuthenticated ?? false)
        {
            <form class="search-container" action="@Url.Action("Search", "Books")" method="GET">
                <i class="fa-search"><img src="~/img/800px-search_icon.svg.png" /></i>
                <input class="input-search" type="text" name="query" placeholder="Search..." />
                <button class="visually-hidden" type="submit"></button>
                <i class="fa-times">x</i>
            </form>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>